### ISSUE TITLE
tests/www/views/test_session.py ~ Failing unit tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#40]
**Total Failures:** 4

**Fail 1:**
https://github.com/sudiptob2/airflow/blob/5be21d2239e38ad27a7855003ea7062aaa6e2117/tests/www/views/test_session.py#L102-L108

We get `TypeError: argument of type 'URL' is not iterable`. The type of the URL is now changed to `string`. Also, it does not contain `/login`. Instead, it contains `/home`. The deactivated user should not been redirected to `/home`. 
Therefore,  it is unclear how to refactor this test.

**Note 1:**
https://github.com/sudiptob2/airflow/blob/5be21d2239e38ad27a7855003ea7062aaa6e2117/tests/www/views/test_session.py#L95-L100
This test is unclear. The name suggests it tests active users. However in line no 97, `user.active=False` was done.

**Fail 2 - 4:**

`AttributeError: 'TestClient' object has no attribute 'cookie_jar'`
The following method is used to get the session cookie. However, after upgrading to `connexion v3` test client being used is the `starllete Test client` which does not have `cookie_jar` attribute.
https://github.com/sudiptob2/airflow/blob/5be21d2239e38ad27a7855003ea7062aaa6e2117/tests/www/views/test_session.py#L31-L33

**Comment by Satoshi-Sh** [comment]
About Faile 2. 

You can use `client.cookies` instead. 
![Screenshot from 2024-03-30 16-55-43](https://github.com/sudiptob2/airflow/assets/73622805/e431baea-df7e-4364-8a0d-369571151625)

**Comment by potiuk** [comment]
Fix to first test in https://github.com/sudiptob2/airflow/pull/64/files explaining what was wrong and how to fix the rest.
