### ISSUE TITLE
 tests/www/views/test_views_acl.py ~ 2 Failing unit tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#43]
Both failures are the same type. `'TestClient' object has no attribute 'session_transaction' `. I think the **Starlette** test client does not have `session_transaction`, hence need to be re-written.

https://github.com/sudiptob2/airflow/blob/6bb05ac0f722323ed00e7ea78dae95e4b1a13d93/tests/www/views/test_views_acl.py#L304-L312

**Comment by potiuk** [comment]
Fix https://github.com/sudiptob2/airflow/pull/66 - or at lest a workaround for now until we find a better way
