### ISSUE TITLE
tests/www/views/test_views_base.py ~ 7 failed tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#45]
1. Most of these parametrized tests are failing. I think the redirection is not working properly and also get a different JSON response.
https://github.com/sudiptob2/airflow/blob/2e8098ae43c0685a8c294d0db71ff4bc07aa95bb/tests/www/views/test_views_base.py#L249-L251

**Comment by sudiptob2** [comment]
Try disabling the admin test and then see if viewer one workes.

**Comment by potiuk** [comment]
Fix: https://github.com/sudiptob2/airflow/pull/65
