### ISSUE TITLE
tests/www/views/test_views_cluster_activity.py ~ 2 Failed tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#49]
All the value of attributes in the `response.json()` is 0. There might be an issue with the configuration of the test client in these tests.
https://github.com/sudiptob2/airflow/blob/61ad3222ff707ef313a8417ab0822fd58988adaf/tests/www/views/test_views_cluster_activity.py#L130-L137

**Comment by potiuk** [comment]
~I think those tests will behave better after https://github.com/sudiptob2/airflow/pull/65 -> seems that every time there was "follow_redirects=True" - the redirects were not followed because the integration was not setting the right Location header on redirect error.~

Nope

**Comment by potiuk** [comment]
Fix in https://github.com/sudiptob2/airflow/pull/67
