### ISSUE TITLE
tests/www/views/test_views_dataset.py ~ 1 Failed Test

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#51]
The response JSON is empty. Not sure about the reason. 
https://github.com/sudiptob2/airflow/blob/61ad3222ff707ef313a8417ab0822fd58988adaf/tests/www/views/test_views_dataset.py#L447-L455

**Comment by potiuk** [comment]
Fix here - also problem with (implicit) db session missing.
