### ISSUE TITLE
tests/www/views/test_views_grid.py ~ 2 Failed tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#55]
Dag run output is not present in the JSON response given by the `test client` after connexion v3 upgrade. Sample response looks like `{'dag_runs': [], 'groups': {'children': [{'extra_links': [], ...`
 Therefore, tests that expect values from `dag_runs` fails.

https://github.com/sudiptob2/airflow/blob/5dfc2281df6adfd679f1b7d86142399dc5f897de/tests/www/views/test_views_grid.py#L165-L183

**Comment by potiuk** [comment]
Fix in https://github.com/sudiptob2/airflow/pull/69
