### ISSUE TITLE
tests/www/views/test_views_home.py ~ 4 Failed tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/airflow#57]
There are still 4 unit tests failing. One of the prominent errors we see in this group of tests is
```
AttributeError: 'FlaskApp' object has no attribute 'appbuilder'
```
I think the problem lies in, how these test users are created. This method of creating test users might not be correct after Connexion v3 upgrade.
https://github.com/sudiptob2/airflow/blob/588b8453afa1c35c0dd5b803757b50e3ebd13888/tests/test_utils/api_connexion_utils.py#L52-L72

**Comment by Satoshi-Sh** [comment]
![Screenshot from 2024-03-30 17-11-49](https://github.com/sudiptob2/airflow/assets/73622805/51e534c8-c1c5-40a7-b6c7-535968f52e51)
This seems fine if you pass app.app instead of app on line 118.

**Comment by potiuk** [comment]
Yes. many of those errors can be solved by using ` app.app` to get to the actual FlaskApplication that is handling the views.
