### ISSUE TITLE
tests/api_connexion/endpoints/test_dataset_endpoint.py ~18 Failed

### ISSUE THREAD

**Issue by Satoshi-Sh** [sudiptob2/airflow#77]
### What happened?

![Screenshot from 2024-04-06 12-44-06](https://github.com/apache/airflow/assets/73622805/19fcd511-c86e-48ef-9840-00e1cbc4642c)

The query parameter validator of Connexion v3 doesn't work properly on the `dataset/events` endpoint. It raises extra query parameter errors even for parameters registered in open API(v1.yaml file). (I believe the v1.yaml file is set correctly.)

Here is [the source code](https://github.com/spec-first/connexion/blob/e6ceb1fc0a13fbe504163592c15e8cac4b52fc6f/connexion/validators/parameter.py#L112C5-L122C1) of Connexion.

@potiuk

**Comment by potiuk** [comment]
Fixed by https://github.com/sudiptob2/airflow/pull/94
