### ISSUE TITLE
Orderby=-state not working - 1 failing test case 

### ISSUE THREAD

**Issue by Satoshi-Sh** [sudiptob2/airflow#95]
In `tests/api_connexion/endpoints/test_mapped_task_instance_endpoint.py` ,`TestGetMappedTaskInstances::test_mapped_task_instances_state_order` cannot order_by=-state. 

https://github.com/sudiptob2/airflow/blob/d4d22e7e75c6b85fcf0fe50230a8d11a76391b8c/airflow/api_connexion/endpoints/task_instance_endpoint.py#L242-L258

The `order_by=-state` block runs on the test case, but it doesn't return the expected result.

**Comment by potiuk** [comment]
It was missing session.commit/close()

**Comment by Satoshi-Sh** [comment]
Thanks for checking, potiuk!!
